[project]
name = "PySide Widgets Project"

[tool.pyside6-project]
files = ["DialogNotificate.py", "dialognotification.cpp", "dialognotification.h", "dialognotification.ui", "form.ui", "mainwindow.py"]
